# Generated by Django 2.2.24 on 2021-12-13 16:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='storage',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
