# Generated by Django 2.2.24 on 2021-12-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20210224_0712'),
        ('account', '0003_account_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vouchers',
            field=models.ManyToManyField(blank=True, related_name='owned_account', to='voucher.Voucher'),
        ),
    ]
