# Generated by Django 2.2.24 on 2021-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
