# Generated by Django 2.2.24 on 2021-12-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_partner_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='Company',
        ),
    ]
